DROP TABLE IF EXISTS weather;

CREATE TABLE weather (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    temperature NUMERIC(5, 2)

);

CREATE INDEX weather_city ON weather (city);